# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9872bd5fcea9e8faf28e166eb4d8ddae379a9132aeb188c71ee1f14e927f250bf4933aab3fc0f544552a73ec624b4b3524a9f2e036665365dbf82bcf50216a3

test:
  secret_key_base: d40b77c70ad713c1876e7f7a538ec83eeab9da64b13725471178a05c1244356be5a27dbf2b7e24781c83e692821a8b7a578af81c132320edbafcd92a8ce3cdac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
